version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.14.1
  resource_class: small

jobs:
  install_lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-10-cache-{{ checksum "./yarn.lock" }}
      - run: yarn install
      - run: yarn lint
      - save_cache:
          key: node-10-cache-{{ checksum "./yarn.lock" }}
          paths:
            - ~/.yarn-cache
            - ./node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Configure git
          command: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts

            git config --global user.email "jenkinsbuilder@documentsmart.com"
            git config --global user.name "xeroxinteractive-builder"
      - run:
          name: Deploy package to npm
          command: yarn deploy

workflows:
  version: 2
  install_lint_deploy:
    jobs:
      - install_lint
      - deploy:
          requires:
            - install_lint
          filters:
            branches:
              only:
                - master
